### ISSUE TITLE
What if the word is not in the API?

### ISSUE THREAD

**Issue by fheravi** [mingiryu/visionary#14]
If the word does not exist, the format of the JSON changes.
At least we have to catch the error and display a message.

**Comment by mingiryu** [comment]
Yep we should display a toast and require the user to put in valid word

**Comment by fheravi** [comment]
@mingiryu 
I think we can still display images even for words that don't exist in the dictionary, but we just need to say the definition does not exist.
As far as the error goes, it is an http error because I believe the serialized JSON is not defined for when the word does not exist..

**Comment by fheravi** [comment]
Solved using try catch statement
