### ISSUE TITLE
List of items/issues remaining

### ISSUE THREAD

**Issue by fheravi** [mingiryu/visionary#15]
- [x] aesthetic: Font size/color, Recyclerview background color, Single Image view, etc
- [x] Remove search bar from action bar
- [x] Going back using Android's feature: When you swipe right to go to previous screen (from images back to search for word), the first time it takes you to a blank screen. If you try another time it'll take you to the main screen. Can this be fixed?
- [x] Back button: Going from Image activity back to main activity resets the definitions and recyclerview. Is there an easy fix?
- [ ] Add more than just definition [part of speech, phonetics, etc.]
- [x] Fix height of definition row: Each definition row in the recylcerview has a large heigh. This needs to be fixed to wrap content instead.
- [x] Recycler view works, but I'm initializing it every time we click search. Can we initialize it once and update data? It's just a better coding practice but not a huge deal
- [ ] Finally if there is time, maybe photos keep getting added as we go down.

**Comment by mingiryu** [comment]
Created tickets for unchecked items #20 #21
